# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180308_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='Label')),
                ('path', models.ImageField(upload_to='resources/', verbose_name='Path')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='catalog.Offer')),
            ],
            options={
                'verbose_name_plural': 'MediaResources',
                'db_table': 'media_resource',
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='banner',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Banner'),
        ),
    ]
