# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180308_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='provider',
            field=models.CharField(max_length=50, verbose_name='Provider'),
        ),
    ]
