# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180308_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(default=123, max_length=36, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
