# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_offer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeritem',
            name='type',
        ),
    ]
