# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_offeritem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='provider',
            field=models.CharField(max_length=36, verbose_name='Provider'),
        ),
    ]
